### ISSUE TITLE
swagger-models - ArrayModel and ArrayProperty are missing support for minItems and maxItems

### ISSUE THREAD

**Issue by benken-parasoft** [swagger-api/swagger-core#1201]
Support for minItems and maxItems appears to be mentioned here in the Swagger 2.0 spec:
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schemaObject

However, ArrayModel and ArrayProperty from the swagger-models API appear to be missing support.  I am using swagger-models to marshall Swagger back and forth.  If the JSON Schema in the literal Swagger document defines an array with minItems and maxItems then this information gets lost parsed.  ArrayModel and ArrayProperty have no fields or methods for getting these values.  Marshalling those objects back to JSON (round-trip) results in those minItems and maxItems being lost.

This deficiency causes a problem for any application that wishes to accurately consume Swagger documents and their embedded JSON Schemas.

Here is a JUnit that demonstrates the problem with ArrayModel and ArrayProperty:

<pre><code>import static org.junit.Assert.*;

import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;

import io.swagger.models.*;
import io.swagger.models.properties.*;
import io.swagger.util.*;

import java.io.*;
import java.util.*;

import org.junit.*;

public class SwaggerTest {
    @Test
    public void testMinMaxItems() throws JsonProcessingException, IOException {
        ObjectMapper mapper = Yaml.mapper();
        JsonNode rootNode = mapper.readTree(SAMPLE_SWAGGER);
        assertNotNull(rootNode);
        Swagger doc = mapper.convertValue(rootNode, Swagger.class);
        Map<String, Model> definitions = doc.getDefinitions();
        assertEquals(2, definitions.size());

        // ArrayModel is missing minItems and maxItems?!?
        Model model = definitions.get("SampleArrayModel");
        assertEquals(ArrayModel.class, model.getClass());
        //ArrayModel arrayModel = (ArrayModel) model;
        //assertEquals(2, arrayModel.minItems());
        //assertEquals(5, arrayModel.maxItems());
        assertEquals("{\"type\":\"array\",\"items\":{\"type\":\"string\"}}",
                mapper.valueToTree(model).toString());

        // ArrayProperty is missing minItems and maxItems?!?
        model = definitions.get("SampleArrayProperty");
        assertEquals(ModelImpl.class, model.getClass());
        ModelImpl modelImpl = (ModelImpl) model;
        Map<String, Property> properties = modelImpl.getProperties();
        assertEquals(1, properties.size());
        Property property = properties.get("myArray");
        assertEquals(ArrayProperty.class, property.getClass());
        //ArrayProperty arrayProperty = (ArrayProperty) property;
        //assertEquals(2, arrayProperty.minItems());
        //assertEquals(5, arrayProperty.maxItems());
        assertEquals("{\"required\":[\"myArray\"],\"properties\":{\"myArray\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}}}",
                mapper.valueToTree(model).toString());
    }

    private static final String SAMPLE_SWAGGER =
            "swagger: \"2.0\"\n" +
            "info:\n" +
            "  version: 1.0.0\n" +
            "  title: Simple test with array\n" +
            "host: fakehostname\n" +
            "basePath: /fakepath\n" +
            "paths:\n" +
            "  /sample:\n" +
            "    post:\n" +
            "      produces:\n" +
            "        - application/json\n" +
            "      parameters:\n" +
            "        - in: body\n" +
            "          name: body\n" +
            "          schema:\n" +
            "            $ref: \"#/definitions/SampleArrayModel\"\n" +
            "      responses:\n" +
            "        200:\n" +
            "          description: OK\n" +
            "definitions:\n" +
            "  SampleArrayModel:\n" +
            "    type: array\n" +
            "    minItems: 2\n" +
            "    maxItems: 5\n" +
            "    items:\n" +
            "      type: string\n" +
            "  SampleArrayProperty:\n" +
            "    required:\n" +
            "      - myArray\n" +
            "    properties:\n" +
            "      myArray:\n" +
            "        type: array\n" +
            "        minItems: 2\n" +
            "        maxItems: 5\n" +
            "        items:\n" +
            "          type: string\n" +
            "";
}</code></pre>

**Comment by webron** [comment]
This should be solved in 1.5.4.

**Comment by benken-parasoft** [comment]
This is still an issue in 1.5.4.  The JUnit I attached demonstrates no change in behavior between 1.5.0 and 1.5.4.  Can this issue please be re-opened?

I notice that ArrayProperty now has fields for minItems and maxItems which is great!  However, the values of those fields in ArrayProperty are always null after parsing my Swagger document.  For example, see "SampleArrayProperty" from my JUnit.  Instead of parsing, I do notice that if I programmatically create an ArrayProperty and set minItems and maxItems then I can marshal the ArrayProperty to JSON and that's fine.  So, things are only broken in one direction.  Marshing ArrayProperty to JSON is fine but parsing from JSON to ArrayProperty looses the values.

Additionally, I notice that ArrayModel still has no fields for minItems and maxItems.  This doesn't help me parse "SampleArrayModel" from my Swagger document, as shown in my JUnit.

I need to be able to parse Swagger documents for my particular use case.  minItems and maxItems are still lost in the example I originally reported.

**Comment by fehguy** [comment]
Sure thing, reopening here.

**Comment by cipresso** [comment]
Hi. I'm also loading JSON schemas into the swagger model and need the minItems and maxItems facets to be supported as well.  Thanks! --Ted

**Comment by conorclifford** [comment]
just noting, this is still present as a limitation in 1.5.8 (we are using it through the swagger-parser project, and need access to various constraints, including at array level.)

Thanks.

**Comment by fehguy** [comment]
Added in master.

**Comment by benken-parasoft** [comment]
Verified on my end.  Thank you.
