### ISSUE TITLE
ResponseHeaders appear in reverse alphabetical order. How do I sort them alphabetically? 

### ISSUE THREAD

**Issue by ahatzz11** [swagger-api/swagger-core#2048]
Here is the `@ApiResponses` annotation I currently have: 

```
@ApiResponses(
        value = {
                @ApiResponse(code = 200, message = "OK", responseContainer = "List",
                        responseHeaders = {
                            @ResponseHeader(name = "aX-RateLimit-Reset", description = "The time, in seconds, until the limit expires and another request will be allowed in. This header will only be present if the limit is being enforced.", response = Integer.class),
                            @ResponseHeader(name = "zX-RateLimit-Remaining", description = "The number of calls remaining before the limit is enforced and requests are bounced.", response = Integer.class),
                            @ResponseHeader(name = "dX-RateLimit-zLimit", description = "The defined maximum number of requests available to the consumer for this API.", response = Integer.class)

                        }
                ),
                @ApiResponse(code = 400, message = "Bad Request"),
                @ApiResponse(code = 404, message = "Not Found"),
                @ApiResponse(code = 415, message = "Unsupported Media Type"),
                @ApiResponse(code = 500, message = "Internal Server Error"),
                @ApiResponse(code = 503, message = "Service Unavailable"),
                @ApiResponse(code = 504, message = "Gateway Timeout"),
                @ApiResponse(code = 505, message = "HTTP Version Not Supported")
        }
)
```

These response headers end up being shown in reverse alphabetical order in the ui, as seen here: 

![](https://puu.sh/sXPo0/6e5cdc9b27.png)

How do I get these to sort alphabetically? I originally assumed that it would be in the order that the `responseHeaders` list is in, but that doesn't seem to be the case. 

Thanks in advance!

**Comment by fehguy** [comment]
Let's isolate the problem by looking in your swagger definition rather than the UI.  What order are they in there?

**Comment by ahatzz11** [comment]
@fehguy Thanks for the quick reply! They appear in reverse alphabetical order in the JSON as well. 

```
"responses":{
  "200":{
    "description":"OK",
    "schema":{
      "type":"object"
    },
    "headers":{
      "zX-RateLimit-Remaining":{
        "type":"integer",
        "format":"int32",
        "description":"The number of calls remaining before the limit is enforced and requests are bounced."
      },
      "dX-RateLimit-zLimit":{
        "type":"integer",
        "format":"int32",
        "description":"The defined maximum number of requests available to the consumer for this API."
      },
      "aX-RateLimit-Reset":{
        "type":"integer",
        "format":"int32",
        "description":"The time, in seconds, until the limit expires and another request will be allowed in. This header will only be present if the limit is being enforced."
      }
    }
  },
```

**Comment by fehguy** [comment]
OK great, then you've got the ticket in the right place.  I'll check into this, it should retain the order inserted as we're using LinkedHashMap

**Comment by ahatzz11** [comment]
Great, thanks!

Also, I couldn't find any good examples of having multiple `@ResponseHeader` annotations in the documentation or online after a bit of searching. If there is a better way of doing it than what I have above, let me know. Maybe something with the `responseContainer` attribute? I don't quite understand what that does yet.

**Comment by fehguy** [comment]
You might check the tests for usage examples

**Comment by ahatzz11** [comment]
Oh nice, I found an example [here](https://github.com/swagger-api/swagger-core/blob/bc6815fa67ef06bd49f0845c45f41532c93ebfe8/modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithApiOperationCode.java#L44-L46). 

If there is any other information you need from me on this issue, let me know.

**Comment by ahatzz11** [comment]
@fehguy I have another odd ordering issue. I can put this in a new issue if you want. 

We're sending many of our params using a custom object, so most of them don't appear in the method params directly. To get these to show up in the documentation, I'm using `@ApiImplicitParam`. The order of these parameters is quite confusing to me. Maybe you can shed some light on what is going on. 

```
@ApiImplicitParams( {
        @ApiImplicitParam(name = "product_id", paramType = "query", dataType = "string", required = true, value = "Product ID to lookup."),
        @ApiImplicitParam(name = "key", paramType = "query", dataType = "string", required = true, value = "Valid API Key."),
        @ApiImplicitParam(name = "channel_id", paramType = "query", dataType = "string"),
        @ApiImplicitParam(name = "disable_location_filter", paramType = "query", dataType = "boolean"),
        @ApiImplicitParam(name = "esfs_locations", paramType = "query", dataType = "int"),
        @ApiImplicitParam(name = "multichannel_option", paramType = "query", dataType = "string"),
        @ApiImplicitParam(name = "field_groups", paramType = "query", dataType = "string"),
        @ApiImplicitParam(name = "inventory_type", paramType = "query", dataType = "string"),
        @ApiImplicitParam(name = "is_parent_id", paramType = "query", dataType = "string"),
        @ApiImplicitParam(name = "limit", paramType = "query", dataType = "int"),
        @ApiImplicitParam(name = "location_available_to_promise_quantity", paramType = "query", dataType = "double"),
        @ApiImplicitParam(name = "location_available_to_release_quantity", paramType = "query", dataType = "double"),
        @ApiImplicitParam(name = "location_ids", paramType = "query", allowMultiple = true, dataType = "string"),
        @ApiImplicitParam(name = "mixed_cart", paramType = "query", dataType = "boolean"),
        @ApiImplicitParam(name = "onlyGetEligibilitiesForSpecifiedMCOption", paramType = "query", dataType = "boolean"),
        @ApiImplicitParam(name = "ignoreComputedLocationEligibility", paramType = "query", dataType = "boolean"),
        @ApiImplicitParam(name = "nearby", paramType = "query", dataType = "string"),
        @ApiImplicitParam(name = "radius", paramType = "query", dataType = "double"),
        @ApiImplicitParam(name = "requested_quantity", paramType = "query", dataType = "double"),
        @ApiImplicitParam(name = "skip_sameday_route_calculation", paramType = "query", dataType = "boolean"),
        @ApiImplicitParam(name = "sort", paramType = "query", dataType = "string"),
        @ApiImplicitParam(name = "stores_limit", paramType = "query", dataType = "int")
    }
)
```

And here's how it ends up in the JSON, and the ui. 

![](https://puu.sh/sY1kp/bc58d97cff.png)

I'd like `product_id` and `key` to be at the top, since they are both required. It doesn't take the order of my annotations, it doesn't go alphabetical, it doesn't prioritize params with a description (`value` in `@ApiImplicitParam`). 

The only thing that _might_ cause this, is that `product_id` is the only param that appears in the method itself. 

```
public ResponseEntity<?> networkAvailabilityJsonResponse(
            @RequestHeader HttpHeaders headers,
            @PathVariable("product_id") String productId,
            @Valid NetworkAvailabilityCmd cmd,
            BindingResult result)
            throws Exception {
            [...]
            }
```

Any ideas?

**Comment by fehguy** [comment]
What version of swagger-core are you using?  Can you please try 1.5.11-SNAPSHOT?

**Comment by ahatzz11** [comment]
Currently on `1.5.10`. I'll try the newest snapshot.

**Comment by fehguy** [comment]
I did find a couple places that weren't using linked hash maps, this is in #2051

**Comment by fehguy** [comment]
This should be fixed, and is tested by https://github.com/swagger-api/swagger-core/blob/3290187ebb746881e19a4b3fe2afc0bf90e92c31/modules/swagger-jaxrs/src/test/java/io/swagger/SimpleReaderTest.java

**Comment by ahatzz11** [comment]
@fehguy I have updated to `1.5.12`, and this issue is still occurring. 

```
@ApiResponses(
        value = {
                @ApiResponse(code = 200,
                        message = "OK",
                        responseHeaders = {
                                @ResponseHeader(name = "A-X-RateLimit-Limit", description = "The defined maximum number of requests available to the consumer for this API.", response = Integer.class),
                                @ResponseHeader(name = "B-X-RateLimit-Remaining", description = "The number of calls remaining before the limit is enforced and requests are bounced.", response = Integer.class),
                                @ResponseHeader(name = "C-X-RateLimit-Reset", description = "The time, in seconds, until the limit expires and another request will be allowed in. This header will only be present if the limit is being enforced.", response = Integer.class)
                        }
                )
        })
```

Here is the JSON output: 

```
"responses":{
  "200":{
    "description":"OK",
    "schema":{
      "type":"object"
    },
    "headers":{
      "C-X-RateLimit-Reset":{
        "type":"integer",
        "format":"int32",
        "description":"The time, in seconds, until the limit expires and another request will be allowed in. This header will only be present if the limit is being enforced."
      },
      "B-X-RateLimit-Remaining":{
        "type":"integer",
        "format":"int32",
        "description":"The number of calls remaining before the limit is enforced and requests are bounced."
      },
      "A-X-RateLimit-Limit":{
        "type":"integer",
        "format":"int32",
        "description":"The defined maximum number of requests available to the consumer for this API."
      }
    }
  }
```

![](https://puu.sh/t4QWW/f0d7cc8864.png)

I've tested this at both the method level, and the class level. The odd ordering issue with my `@ApiImplicitParam` annotations is still happening as well. 

`swagger-annotations`, `swagger-core` and `swagger-models` are all on `1.5.12`

**Comment by ahatzz11** [comment]
I've been doing some more playing with this, and now I'm running into other odd situations. 

```
@ApiResponse(code = 200,
                        message = "OK",
                        responseHeaders = {
                                @ResponseHeader(name = "aaa", description = "The defined maximum number of requests available to the consumer for this API.", response = Integer.class),
                                @ResponseHeader(name = "bbb", description = "The number of calls remaining before the limit is enforced and requests are bounced.", response = Integer.class),
                                @ResponseHeader(name = "ccc", description = "The time, in seconds, until the limit expires and another request will be allowed in. This header will only be present if the limit is being enforced.", response = Integer.class)
                        }
                )
```

gives me...

```
"responses":{
  "200":{
    "description":"OK",
    "schema":{
      "type":"object"
    },
    "headers":{
      "aaa":{
        "type":"integer",
        "format":"int32",
        "description":"The defined maximum number of requests available to the consumer for this API."
      },
      "ccc":{
        "type":"integer",
        "format":"int32",
        "description":"The time, in seconds, until the limit expires and another request will be allowed in. This header will only be present if the limit is being enforced."
      },
      "bbb":{
        "type":"integer",
        "format":"int32",
        "description":"The number of calls remaining before the limit is enforced and requests are bounced."
      }
    }
  }
```

I'm not sure what it's doing, but order isn't being persevered.

**Comment by ahatzz11** [comment]
@fehguy Any ideas on the odd examples above?
