### ISSUE TITLE
Problem with subresource detection when using dependency injection in Jersey 2

### ISSUE THREAD

**Issue by joscarsson** [swagger-api/swagger-core#394]
This works fine:
```
@Path("/{objectId: [a-fA-F0-9]{32}}")
@ApiOperation(value = "subresource", response = SomeSubResource.class)
public SomeSubResource continueInSubResource() {
  return new SomeSubResource();
}
```

The problem occurs when using Jersey dependency injection for creating the resources. The code is then changed to this:
```
@Path("/{objectId: [a-fA-F0-9]{32}}")
@ApiOperation(value = "subresource", response = SomeSubResource.class)
public Class<SomeSubResource> continueInSubResource() {
  return SomeSubResource.class;
}
```

That is, we only tell Jersey which type of class we want, and Jersey dependency injection instantiates the correct class (passing in the dependencies to the constructor automatically). However, this seems to confuse swagger, which does not detect this subresource at all.

**Comment by mbde** [comment]
I am using Jersey 1.18, but maybe the issue is related.
In my [example app]( /mbde/swagger-example) several `@Path` annotations are used to describe an endpoint, also illustrated in the following snippets.
jerseys servlet url-pattern is `/rest/*` and with the `StringResource`, the path goes on with `/string/static/`
````java
@Path("/string")
public class StringResource {

    @Path("static")
    public Class<StaticStringResource> getStaticStringResource() {
        return StaticStringResource.class;
    }
}
````
Class StaticStringResource is the subresource and is preceeded by the path : `/string/static/` as also annotated in `@Api`
The method paths (with base path) are `/rest/string/static/hello` and `/rest/string/static/{string}`
````java
Api(value ="/string/static")
public class StaticStringResource {

    @ApiOperation( value ="hello world")
    @GET
    @Path("/hello")
    public String getStaticHelloWorld(){
        return "Hello World";
    }


    @ApiOperation( value ="identity function")
    @GET
    @Path("{string}")
    public String getStatic(@PathParam("string") String string){
        return string;
    }
}
````
The json output of [`/rest/string/static/`](http://localhost:8080/rest/api-docs/string/static) is as follows:
````json


{
  "apiVersion": "0.1",
  "swaggerVersion": "1.2",
  "basePath": "http://localhost:8080/rest",
  "resourcePath": "/string/static",
  "apis": [
    {
      "path": "/{string}",
      "operations": [
        {
          "method": "GET",
          "summary": "identity function",
          "notes": "",
          "type": "string",
          "nickname": "getStatic",
          "parameters": [
            {
              "name": "string",
              "required": true,
              "type": "string",
              "paramType": "path",
              "allowMultiple": false
            }
          ]
        }
      ]
    },
    {
      "path": "/hello",
      "operations": [
        {
          "method": "GET",
          "summary": "hello world",
          "notes": "",
          "type": "string",
          "nickname": "getStaticHelloWorld",
          "parameters": []
        }
      ]
    }
  ]
}
````
Since the resourcePath is not feeded by the jerseys `@Path` annotation the method paths are somewhat partial.
If i click the "Try it out!" button on `hello` the url is `http://localhost:8080/rest/hello`
It seems the `@Path` annotations in StringResource are not used.

**Comment by webron** [comment]
@mbde - which version of swagger-core do you use?

**Comment by webron** [comment]
@mbde - never mind, just saw the original issue.

**Comment by mbde** [comment]
@webron and @fehguy : I think my issue is not relly related with the original issue.
Is the @Path annotation only used in class/method of the endpoint?

**Comment by webron** [comment]
As opposed to?

**Comment by mbde** [comment]
as in the example, the path to the endpoint si composed of several `@Path` usages in different classes. 
This usage of these annotations (e.g. StringResource), doesnt seem to work well with swagger

**Comment by webron** [comment]
Fixed in develop_2.0.

**Comment by querua** [comment]
Hi I am still experiencing problem with "class-based" subresources which was described here and subsequently fixed in https://github.com/swagger-api/swagger-core/pull/994

so when I am using following approach subresources  are not getting detected at all
```
public Class<SomeSubResource> continueInSubResource() {
  return SomeSubResource.class;
}
```
however when I tried following, subresources are detected
```
@Context
ResourceContext resourceContext;

public SomeSubResource continueInSubResource() {
  return resourceContext.getResource(SomeSubResource.class);
}
```
We are using Jersey v2.25.1, swagger-annotations v1.5.13 and  swagger-maven-plugin v3.1.2

Could somebody please reopen this issue? Are provided information sufficient?
