### ISSUE TITLE
Make ModelConverterContext swappable

### ISSUE THREAD

**Issue by nikita2206** [swagger-api/swagger-core#4718]
Currently, the `ModelConverterContext` is instantiated statically from within the `ModelConverters` class. The context happens to contain some logic that seems to be hard (or impossible) to modify in any other way, other than by extending the `ModelConverterContext` and overriding the `resolve()` method.

## Problem

Namely, we would like to add clever handling of `Optional<...>` properties of objects, such that the OAS component that contains such property would specify `nullable = true` for it. However, because the `ModelConverterContextImpl` has the following line, we lose the information about Optional wrapper very early on, which makes it impossible for us to use the existing ModelConverter extension points to implement this:
```java
AnnotatedType aType = ReferenceTypeUtils.unwrapReference(type);
```

## Solution

If you don't see any immediate issues with this, I'd like to create a PR adding a `ModelConverterContextFactory` factory which will be settable on a `ModelConverters` singleton object, like the following:
```java
ModelConverters.getInstance()
  .setContextFactory(converters -> new CustomContext(converters));
```

**Comment by Mattias-Sehlstedt** [comment]
I believe your use case tied to `Optional<T>` interpretation should have been resolved with https://github.com/swagger-api/swagger-core/pull/5042?

**Comment by nikita2206** [comment]
@Mattias-Sehlstedt yes i believe the `required` works correctly for us now, thank you! I think it is still not being set for collection fields, but I haven't confirmed if they are actually not required with our Jackson set up
