### ISSUE TITLE
[Bug]: Superfluous sibling $ref when using oneOf in Schema annotation - OAS 3.1

### ISSUE THREAD

**Issue by bostrom** [swagger-api/swagger-core#4959]
## Description of the problem/issue

Using `oneOf` in an OAS 3.1 `@Schema` annotation results in an additional `$ref` in the root of the property. 

This happens both when using two classes, and with one class, and allowing `null` as property value.

Expected behaviour is that `$ref`s would only be used inside the `oneOf` array.

## Affected Version

2.2.36

### Allowing `myProperty` to be one of two classes:

Using:
```java
    @Schema(oneOf = {SomeDto.class, OtherDto.class})
```

Actual outcome:
```yaml
components:
  schemas:
    MyDto:
      type: object
      properties:
        myProperty:
          $ref: "#/components/schemas/SomeDto"
          oneOf:
            - $ref: "#/components/schemas/SomeDto"
            - $ref: "#/components/schemas/OtherDto"
```

Expected outcome:
```yaml
components:
  schemas:
    MyDto:
      type: object
      properties:
        myProperty:
          oneOf:
            - $ref: "#/components/schemas/SomeDto"
            - $ref: "#/components/schemas/OtherDto"
```

### Allowing `myProperty` to be a class or `null`:

Using:
```java
    @Schema(oneOf = {SomeDto.class}, types = {"object", "null"})
```

Actual outcome:
```yaml
components:
  schemas:
    MyDto:
      type: object
      properties:
        myProperty:
          type:
            - object
            - "null"
          $ref: "#/components/schemas/SomeDto"
          oneOf:
            - $ref: "#/components/schemas/SomeDto"
```

Expected outcome:
```yaml
components:
  schemas:
    MyDto:
      type: object
      properties:
        myProperty:
          type:
            - object
            - "null"
          oneOf:
            - $ref: "#/components/schemas/SomeDto"
```

**Comment by djankows** [comment]
Thanks for the report @bostrom ! 
I tried to reproduce this on swagger-core 2.2.36 targeting OAS 3.1 with POJOs like:
```
    static class SomeDto {
        public String a;
    }

    static class OtherDto {
        public Integer b;
    }

    static class MyDto {
        @Schema(oneOf = { SomeDto.class, OtherDto.class })
        public Object payload;
    }
```

by passing the MyDto class to ModelConverters resolveAsResolvedSchema() or simply building OpenAPI and printing it with Yaml31.pretty(), but for both cases there were only $refs under oneOf.

My result:
```
components:
  schemas:
    MyDto:
      type: object
      properties:
        payload:
          type: object
          oneOf:
          - $ref: "#/components/schemas/SomeDto"
          - $ref: "#/components/schemas/OtherDto"
    OtherDto:
      type: object
      properties:
        b:
          type: integer
          format: int32
    SomeDto:
      type: object
      properties:
        a:
          type: string
```

It would help a lot if you could share a minimal repro and exact steps.

**Comment by markoka** [comment]
There is a problem with nullable properties. If the MyDto of @djankows example is changed like this:
```
static class MyDto {

    @Schema(types = {"object", "null"})
    public SomeDto payload;
}
```

Then the result is:
```
 MyDto:
      type: object
      properties:
        payload:
          type:
          - object
          - "null"
          $ref: "#/components/schemas/SomeDto"
```

Because any sibling elements of $ref are ignored, the payload property is not nullable.
For the payload property to be nullable, the result should be something like this:

```
  MyDto:
      type: object
      properties:
        payload:
          type:
          - object
          - "null"
          oneOf:
          - $ref: "#/components/schemas/SomeDto"
```

If oneOf if explicitly used in MyDto:
```
static class MyDto {

    @Schema(oneOf = {SomeDto.class}, types = {"object", "null"})
    public SomeDto payload;
}
```

Then the result has an additional $ref as @bostrom reported:
```
   MyDto:
      type: object
      properties:
        payload:
          type:
          - object
          - "null"
          $ref: "#/components/schemas/SomeDto"
          oneOf:
          - $ref: "#/components/schemas/SomeDto"
```

**Comment by bostrom** [comment]
I also had a typo in my original description:

```java
    @Schema(oneOf = {SomeDto.class, OtherDto.class}, types = {"object", "null"})
```

Should be, and has now been changed to
```java
    @Schema(oneOf = {SomeDto.class}, types = {"object", "null"})
```

**Comment by ewaostrowska** [comment]
Hi [bostrom](https://github.com/bostrom), 
Thanks for reporting the issue! It should be fixed with https://github.com/swagger-api/swagger-core/commit/9f5bf1d130220396262a4a660b0df15b3acafce1

**Comment by bostrom** [comment]
@ewaostrowska seems this is still broken in swagger-core@2.2.41. 

Take for example these three properties:

```java
public class SomeDto {
    @Schema(types = {"object"})
    private CustomerDto customer;

    @Schema(types = {"object"}, oneOf = {CustomerDto.class})
    private CustomerDto owner;

    @Schema(types = {"object", "null"}, oneOf = {CustomerDto.class})
    private CustomerDto manager;
}
```

Those three generate this in swagger.yaml:
```yaml
        customer:
          type: object
          $ref: '#/components/schemas/CustomerDto'
        owner:
          type: object
          $ref: '#/components/schemas/CustomerDto'
          oneOf:
            - $ref: '#/components/schemas/CustomerDto'
        manager:
          type:
            - object
            - 'null'
          $ref: '#/components/schemas/CustomerDto'
          oneOf:
            - $ref: '#/components/schemas/CustomerDto'

```
As you can see, the ones with `oneOf` still generate an extra `$ref` before the `oneOf`.

**Comment by bostrom** [comment]
My apologies, the fix does indeed work, instead the issue is how the property types are defined in the class and annotations. I made a [small demo project](https://github.com/bostrom/spring-4-openapi-3.1-demo) to investigate the specifics, and here's a brief summary:

If the type is defined explicitly both in the property _and_ the annotation, then swagger adds two $refs:

```java
    @Schema(types = {"object", "null"}, oneOf = {CustomerDto.class})
    private CustomerDto manager;
```
indeed becomes
```yaml
        manager:
          type:
            - object
            - 'null'
          $ref: '#/components/schemas/CustomerDto'
          oneOf:
            - $ref: '#/components/schemas/CustomerDto'
```
due to `CustomerDto` being defined both in `private CustomerDto owner` and `oneOf = {CustomerDto.class}`.

However, if we omit the `oneOf`, then swagger doesn't add the second `$ref`.
```java
    @Schema(types = {"object", "null"}
    private CustomerDto manager;
```
becomes
```yaml
        manager:
          type:
            - object
            - 'null'
          $ref: '#/components/schemas/CustomerDto'
```
as expected. And as siblings to `$ref` are allowed in OAS 3.1 (but not in 3.0) this is a valid schema. 

Since this issue was about the use `oneOf`, then the correct way to create polymorphic properties would be to use the `Object` type together with `oneOf`. 
```java
  @Schema(types = { "object", "null" }, oneOf = { CreditCardDto.class, BankTransferDto.class })
  private Object paymentMethod;
```
becomes, as expected,
```yaml
        paymentMethod:
          type:
          - object
          - "null"
          oneOf:
          - $ref: "#/components/schemas/CreditCardDto"
          - $ref: "#/components/schemas/BankTransferDto"
```
